# Setup
title:               kevin s chen
tagline:             'ramblings'
description:         'kevin chen<br>mit eecs 23<br>kschen at mit dot edu<br>thought bubbles & baubles'
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              kevin chen
  url:               https://twitter.com/kechens_
  email:             kschen@mit.edu

# Gems
plugins:
  - jekyll-paginate

# Custom vars
google_analytics_id: UA-146052-15
